**NumPy Lab Assignment**

**Exercise 1: Cast a python list to a numpy array**


In [45]:
#import numpy
import numpy as np

#create a list
jc_list = ['a','b','c'] 

#display the list
print (jc_list)
    
print ("This is done by John Callahan")

['a', 'b', 'c']
This is done by John Callahan


In [49]:
#cast that list as an array
print (np.array(jc_list))
#we get back an array as the container for that list object
# note this is one dimensional array

print ("This is done by John Callahan")

['a' 'b' 'c']
This is done by John Callahan


In [48]:
#  assign this to an array
arr = np.array(jc_list) 
# display arr
print (arr)

print ("This is done by John Callahan")

['a' 'b' 'c']
This is done by John Callahan


**Exercise 2: Cast a list of lists to a two dimensional numpy arrary**

In [51]:
#mat is a list of four lists 
mat1=[[10,20,30], [41,52,62], [71,18,19],[100,200,230]]

# let us display it
print (mat1)

print ("This is done by John Callahan")

[[10, 20, 30], [41, 52, 62], [71, 18, 19], [100, 200, 230]]
This is done by John Callahan


In [52]:
#let us cast this to an array
print (np.array(mat1)) 

# I will get back two dimensional array. The two sets of brackets and the way it is displayed indicates
# that it is a two dimensional array

print ("This is done by John Callahan")

[[ 10  20  30]
 [ 41  52  62]
 [ 71  18  19]
 [100 200 230]]
This is done by John Callahan


**Exercise 3: Using NumPy generation methods arrange to create arrays**

In [53]:
#use arrange method to create the following numpy array [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
print (np.arange (0,16))

print ("This is done by John Callahan")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
This is done by John Callahan


In [54]:
#import numpy as np
import numpy as np

print ("This is done by John Callahan")

This is done by John Callahan


In [55]:
#np.arrange using start, stop, and step arguments to create the following numpy array [0,4,8,12,16,20,24]

print (np.arange (0,25,4))

print ("This is done by John Callahan")

[ 0  4  8 12 16 20 24]
This is done by John Callahan


**Exercise 4:**

In [56]:
#create the two dimensional 4 x 4 numpy array of zeros

print (np.zeros((4,4)))

print ("This is done by John Callahan")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
This is done by John Callahan


In [57]:
#create the two dimensional 5 x 5 numpy array of ones

print (np.ones ((5,5)))

print ("This is done by John Callahan")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
This is done by John Callahan


In [58]:
#create a two dimensianal identity matrix of size 6 x6

print (np.eye(6))

print ("This is done by John Callahan")

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
This is done by John Callahan


In [7]:
#Create numpy array from 0 to 19 elements with a length of 20
arr=np.arange(20)

#display arr
print (arr)

print ("This is done by John Callahan")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
This is done by John Callahan


**Exericse 5*

In [59]:
#consider the following numpy array
mylist = [[10, 21, 32, 40],[3, 4, 5, 6], [50, 6, 70, 8]]
#cast it to an array arr2

arr2 = np.array(mylist)
    
#find max

print (arr2.max())

print ("This is done by John Callahan")

70
This is done by John Callahan


In [60]:
#find min

print (arr2.min())

print ("This is done by John Callahan")

3
This is done by John Callahan


In [61]:
#Find the location of the min value 

print (arr2.argmin())

print ("This is done by John Callahan")

4
This is done by John Callahan


**Exercise 6-NumPy Scalar Operations**

In [15]:
#import numpy as np
import numpy as np

print ("This is done by John Callahan")

This is done by John Callahan


In [16]:
#to hide warnings from jupyter notebook

import warnings;
warnings.simplefilter('ignore')

print ("This is done by John Callahan")

This is done by John Callahan


In [63]:
#consider the following numpy array
list2 = [[11, 21, 3, 4],[3, 41, 5, 6], [51, 6, 71, 8]]

#cast it to a numpy array arr2

arr2 = np.array(list2)

print ("This is done by John Callahan")

This is done by John Callahan


In [64]:
#multiply each element by 6

print (arr2 * 6)

print ("This is done by John Callahan")

[[ 66 126  18  24]
 [ 18 246  30  36]
 [306  36 426  48]]
This is done by John Callahan


In [65]:
#raise every element to the power 4
 
print (arr2 **4)

print ("This is done by John Callahan")

[[   14641   194481       81      256]
 [      81  2825761      625     1296]
 [ 6765201     1296 25411681     4096]]
This is done by John Callahan


**Exercise 6 descriptive statistics**

In [66]:
# get the average of numbers in a numpy array arr2

print (np.mean(arr2))

print ("This is done by John Callahan")

19.166666666666668
This is done by John Callahan


In [44]:
# get the median of numbers in a numpy array aar2

print (np.median(arr2))

print ("This is done by John Callahan")

7.0
This is done by John Callahan


- Let us create another numpy array that has elements repeated more than once
- arr3=np.append([10, 20, 30], [[4, 5, 6], [40, 40, 60]])

In [40]:
#create the array mentioned above
 
arr3=np.append([10, 20, 30], [[4, 5, 6], [40, 40, 60]])

#import the required library

from scipy import stats

#compute the mode for arr3
#get the mode of number in a numpy array


# get the mode of arr3
jcmode=stats.mode(arr3)

#print the mode

print (jcmode)

print ("This is done by John Callahan")

ModeResult(mode=40, count=2)
This is done by John Callahan


##### **Exercise 7**
- Get the min max mean vairance skewnees and kurtosis for the following numpy array
- b= np. arrange (15)

In [67]:
#create a numpy array using arange

b = np.arange(15)

#import required library

from scipy import stats

#Get all the required values in one statment

print (stats.describe(b))

print ("This is done by John Callahan")

DescribeResult(nobs=15, minmax=(0, 14), mean=7.0, variance=20.0, skewness=0.0, kurtosis=-1.210714285714286)
This is done by John Callahan


**Exercise 8: Slicing Two Dimensional Array ---Matrix**
 - Consider the following two dimensional array
 - arr4 = np.array([[35,20,15],[40,115,25],[15,20,75],[30,10,35]])

In [32]:
#create the array arr4 mentioned above

arr4 = np.array([[35,20,15],[40,115,25],[15,20,75],[30,10,35]])

#print it

print (arr4)

print ("This is done by John Callahan")

[[ 35  20  15]
 [ 40 115  25]
 [ 15  20  75]
 [ 30  10  35]]
This is done by John Callahan


In [69]:
##to get  the second and third row of arr4

print (arr4[1:3])

print ("This is done by John Callahan")

[[ 40 115  25]
 [ 15  20  75]]
This is done by John Callahan


In [70]:
#if you want submatrices of a matrix not elements you can use : for slice notations
#let us say that I want to grap 20,15,115,25,20,75 i.e. the submatrix at the top right corner

print (arr4[:2,1:])

print ("This is done by John Callahan")

[[ 20  15]
 [115  25]]
This is done by John Callahan


In [71]:
#let us say that we want to know all the elements of the array arr4 that are > 30

print (arr4 >30)

print ("This is done by John Callahan")

[[ True False False]
 [ True  True False]
 [False False  True]
 [False False  True]]
This is done by John Callahan
